### ISSUE TITLE
Doesnt work on Alpine Linux

### ISSUE THREAD

**Issue by djpate** [imdrasil/sam.cr#18]
I've been trying to setup a basic project using `crystallang/crystal:1.0.0-alpine`

my shards was setup as 

```
name: app
version: 0.1.0
dependencies:
  graphql:
    github: graphql-crystal/graphql
  kemal:
    github: kemalcr/kemal
  jennifer:
    github: imdrasil/jennifer.cr
    version: "~> 0.11.1"
  pg:
    github: will/crystal-pg
  sam:
    github: imdrasil/sam.cr
    version: 0.4.1
```

and my `sam.cr`

```
#require "./config/*" 
require "sam"
#load_dependencies "jennifer"

task "name" do
end

Sam.help
```

Trying to run `crystal sam.cr help` yields the following error

```
/app # crystal sam.cr help
--: line 1: tput: not found
/usr/share/crystal/src/string.cr:430:5 in 'to_i32'
/usr/share/crystal/src/string.cr:331:5 in 'to_i'
lib/sam/src/sam/shell_table.cr:11:16 in 'initialize'
lib/sam/src/sam/shell_table.cr:10:5 in 'new'
lib/sam/src/sam/tasks.cr:6:8 in '->'
/usr/share/crystal/src/primitives.cr:255:3 in 'call'
lib/sam/src/sam/execution.cr:19:7 in 'invoke'
lib/sam/src/sam.cr:35:5 in 'invoke'
lib/sam/src/sam.cr:53:7 in 'process_tasks'
lib/sam/src/sam.cr:41:5 in 'help'
sam.cr:8:1 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
/usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
/usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
???
Invalid Int32: 
```

Switching to `crystallang/crystal:1.0.0` fixes the problem
